export const styles = {
  link: {
    textDecoration: "none",
    color: "inherit",
  },
  card: {
    width: "100%",
    maxWidth: 260,
    borderRadius: 4,
    overflow: "hidden",
    bgcolor: "background.paper",
    boxShadow: "0 6px 18px rgba(0,0,0,0.12)",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    "&:hover": {
      transform: "translateY(-8px) scale(1.05)",
      boxShadow: "0 14px 28px rgba(0,0,0,0.25)",
    },
  },
  mediaBox: {
    position: "relative",
    overflow: "hidden",
  },
  media: {
    height: 300,
    objectFit: "cover",
    transition: "transform 0.4s ease, filter 0.4s ease",
    filter: "brightness(0.92)",
    "&:hover": {
      transform: "scale(1.08)",
      filter: "brightness(1)",
    },
  },
  ratingBox: {
    position: "absolute",
    bottom: 10,
    right: 10,
    bgcolor: "rgba(0,0,0,0.6)",
    backdropFilter: "blur(4px)",
    px: 1.2,
    py: 0.4,
    borderRadius: 2.5,
    display: "flex",
    alignItems: "center",
    gap: 0.6,
    color: "#FFD700",
    fontWeight: 600,
    fontSize: "0.85rem",
  },
  content: {
    p: 2,
  },
  title: {
    fontWeight: 700,
    fontSize: "1rem",
    letterSpacing: "0.3px",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    lineHeight: 1.4,
  },
  genresBox: {
    display: "flex",
    flexWrap: "wrap",
    gap: 0.6,
    mt: 1.2,
  },
};
