export const styles = {
  link: {
    textDecoration: "none",
    color: "inherit",
  },
  card: {
    width: "100%",
    maxWidth: 260,
    height: 420,            // 🔥 altura fija
    display: "flex",
    flexDirection: "column",
    borderRadius: 5,
    overflow: "hidden",
    bgcolor: "rgba(255,255,255,0.1)",
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.2)",
    boxShadow: "0 8px 20px rgba(0,0,0,0.25)",
    transition: "transform 0.4s ease, box-shadow 0.4s ease",
    "&:hover": {
      transform: "translateY(-8px) rotate3d(1,1,0,6deg) scale(1.05)",
      boxShadow: "0 20px 40px rgba(0,0,0,0.35)",
    },
  },
  mediaBox: {
    position: "relative",
    overflow: "hidden",
  },
  media: {
    height: 220, // 🔥 menos alto para que deje espacio al contenido
    objectFit: "cover",
    transition: "transform 0.5s ease, filter 0.5s ease",
    filter: "brightness(0.95) contrast(1.05)",
    "&:hover": {
      transform: "scale(1.12) rotate(1deg)",
      filter: "brightness(1)",
    },
  },
  ratingBox: {
    position: "absolute",
    bottom: 8,
    right: 8,
    bgcolor: "rgba(0,0,0,0.55)",
    backdropFilter: "blur(6px)",
    px: 1.2,
    py: 0.4,
    borderRadius: 3,
    display: "flex",
    alignItems: "center",
    gap: 0.5,
    color: "#FFD700",
    fontWeight: 700,
    fontSize: "0.85rem",
  },
  content: {
    p: 2,
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  title: {
    fontWeight: 800,
    fontSize: "1rem",
    letterSpacing: "0.4px",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    lineHeight: 1.4,
  },
  genresBox: {
    display: "flex",
    flexWrap: "wrap",
    gap: 0.5,
    mt: 1,
  },
};
